[package]
name = "rustserini"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bert = "0.20.0"
ndarray = "0.15.6"
tch = "0.10.0"
rust_tokenizers = "8.1.0"
